"""add oath fields to user model

Revision ID: 59940949604b
Revises: c497fa9cbc64
Create Date: 2025-11-05 10:48:50.272693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59940949604b'
down_revision = 'c497fa9cbc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('oauth_access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('oauth_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('oauth_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('oauth_token_expires')
        batch_op.drop_column('oauth_refresh_token')
        batch_op.drop_column('oauth_access_token')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
