"""add oauth tokens and sync tracking email_accounts

Revision ID: dbe12c666323
Revises: e0cf692d2359
Create Date: 2025-11-05 14:07:23.402549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe12c666323'
down_revision = 'e0cf692d2359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sync_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_synced_email_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_column('last_synced_email_id')
        batch_op.drop_column('sync_status')
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('token_expires')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###
